// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHIkAWRbYA3u0dlOm0GQ-vMkkQNOMEnj4',
    appId: '1:57749242706:web:ea60299355d8df0b18b08b',
    messagingSenderId: '57749242706',
    projectId: 'live-score-app-15',
    authDomain: 'live-score-app-15.firebaseapp.com',
    storageBucket: 'live-score-app-15.firebasestorage.app',
    measurementId: 'G-QV2269YL0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-hRjAMkEyIIiyTtlLnGQ7rWrPocge8o8',
    appId: '1:57749242706:android:36f89e05541d19a618b08b',
    messagingSenderId: '57749242706',
    projectId: 'live-score-app-15',
    storageBucket: 'live-score-app-15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXSoBjGNH__9VRn0EqGHefvbQFOa74LCs',
    appId: '1:57749242706:ios:558703d4e5b5400418b08b',
    messagingSenderId: '57749242706',
    projectId: 'live-score-app-15',
    storageBucket: 'live-score-app-15.firebasestorage.app',
    iosBundleId: 'com.example.liveScoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXSoBjGNH__9VRn0EqGHefvbQFOa74LCs',
    appId: '1:57749242706:ios:558703d4e5b5400418b08b',
    messagingSenderId: '57749242706',
    projectId: 'live-score-app-15',
    storageBucket: 'live-score-app-15.firebasestorage.app',
    iosBundleId: 'com.example.liveScoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHIkAWRbYA3u0dlOm0GQ-vMkkQNOMEnj4',
    appId: '1:57749242706:web:656e9dbb1c80046c18b08b',
    messagingSenderId: '57749242706',
    projectId: 'live-score-app-15',
    authDomain: 'live-score-app-15.firebaseapp.com',
    storageBucket: 'live-score-app-15.firebasestorage.app',
    measurementId: 'G-2ZDQYQKT9N',
  );
}
